sudo: false

language: php

branches:
  except:
    - /^release-.*$/
    - /^ghgfk-.*$/

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.local
    - zf-mkdoc-theme

env:
  global:
    - SITE_URL=https://zendframework.github.io/zend-json-server
    - GH_USER_NAME="Matthew Weier O'Phinney"
    - GH_USER_EMAIL=matthew@weierophinney.net
    - GH_REF=github.com/zendframework/zend-json-server.git
    - secure: "KvztcHanoXLkqi+yL3o5el7ypu/jcyHqKy0VtOKGB483sg2wn6wJyAuVLBJscmzgazjPzQa57MBe9an7OOpuoJNPtE5m9huk41KByK2ibzMnC4F7D8lox5CUoV0jRaohYQmpZitbj/BKPlFbYaT42d+/R2o9CEQUJ4T3nYltzAydvB3T1CJE1u7HtZ8mB/Kgkfjqcyx+/bnmvmeGlwop4rDxHmEmrfApdWSUMSKUKjJqUlZt0ASpa2fJy3HL4don6WV1ufPcKVI7bQN1dkn+zZhW5zQ7PRg0hMEMxEMC8MLyLZvDXxL4rUmt2i3I0NtK6E357QdoX13NQKJZiH47jFpJA3DFQl2vE7Vu3kEkMqsrM2fbp9xTCyN9Gg5ZHueUd+iUxVCTy5Twlqt8MqBd2Z4tbljOsgBQkRuKxRg+JkNcWGM5RIWhA169nGY25867Bah/hh25blpsj77RVsvJdeUzAqCHWm5ey+2rNcUWbJXUK2nQdlonCLNsP0LweA5344GFFw+U+93btEw/5mpADbjhaYuZKXhMOcnqJgTGghxkp0cnExb7w5p6KxAsQ+E/C5X7RDwwhaTb6LUuKrTgar4/3RVUIqujdVVUntB1161S6Qnut1TqdaRHbgGOBSlCNWAB960icfdNbN+y4mtJZf9AVgvkoN8QGlncVPF+6GI="

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env:
        - CS_CHECK=true
    - php: 5.6
      env:
        - TEST_COVERAGE=true
        - DEPLOY_DOCS="$(if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then echo -n 'true' ; else echo -n 'false' ; fi)"
        - PATH="$HOME/.local/bin:$PATH"
    - php: 7
    - php: hhvm 
  allow_failures:
    - php: hhvm

notifications:
  irc: "irc.freenode.org#zftalk.dev"
  email: false

before_install:
  - if [[ $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - travis_retry composer self-update
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer require --dev --no-update satooshi/php-coveralls ; fi

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer test-coverage ; else composer test ; fi
  - if [[ $CS_CHECK == 'true' ]]; then composer cs-check ; fi
  - if [[ $DEPLOY_DOCS == "true" && "$TRAVIS_TEST_RESULT" == "0" ]]; then wget -O theme-installer.sh "https://raw.githubusercontent.com/zendframework/zf-mkdoc-theme/master/theme-installer.sh" ; chmod 755 theme-installer.sh ; ./theme-installer.sh ; fi

after_success:
  - if [[ $DEPLOY_DOCS == "true" ]]; then echo "Preparing to build and deploy documentation" ; ./zf-mkdoc-theme/deploy.sh ; echo "Completed deploying documentation" ; fi

after_script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer upload-coverage ; fi
